#ifndef __OPLUS_MMS_WIRED_H__
#define __OPLUS_MMS_WIRED_H__

#include "oplus_mms.h"

enum wired_topic_item {
	WIRED_ITEM_PRESENT,
	WIRED_ITEM_ONLINE,
	WIRED_ITEM_ERR_CODE,
	WIRED_ITEM_CHG_TYPE,
	WIRED_ITEM_BC12_COMPLETED,
	WIRED_ITEM_CC_MODE,
	WIRED_ITEM_CC_DETECT,
	WIRED_ITEM_USB_STATUS,
	WIRED_ITEM_USB_TEMP_VOLT_L,
	WIRED_ITEM_USB_TEMP_VOLT_R,
	WIRED_ITEM_USB_TEMP_L,
	WIRED_ITEM_USB_TEMP_R,
	WIRED_ITEM_PRE_OTG_ENABLE,
	WIRED_ITEM_OTG_ENABLE,
	WIRED_ITEM_CHARGER_CURR_MAX,
	WIRED_ITEM_CHARGER_VOL_MAX,
	WIRED_ITEM_CHARGER_VOL_MIN,
	WIRED_TIME_ABNORMAL_ADAPTER,
	WIRED_TIME_TYPEC_STATE,
	WIRED_ITEM_REAL_CHG_TYPE,
	WIRED_ITEM_VBUS,
	WIRED_ITEM_ONLINE_STATUS_ERR,
	WIRED_ITEM_CHARGING_DISABLE,
	WIRED_ITEM_COEXISTENCE,
	WIRED_ITEM_PD_COMPLETED,
	WIRED_ITEM_ICL_DONE_STATUS,
	WIRED_ITEM_VBUS_VOL_TYPE,
	WIRED_ITEM_BUCK_EIS_CURRENT_RATE,
};

enum oplus_wired_cc_detect_status {
	CC_DETECT_NULL,
	CC_DETECT_NOTPLUG,
	CC_DETECT_PLUGIN,
};

typedef enum {
	BCC_CURR_DONE_UNKNOW = 0,
	BCC_CURR_DONE_REQUEST,
	BCC_CURR_DONE_ACK,
}OPLUS_BCC_CURR_DONE_STATUS;

typedef enum
{
	OPLUS_LPD_SEL_SBU1 = 0x0,
	OPLUS_LPD_SEL_SBU2,
	OPLUS_LPD_SEL_SBU1_400K,
	OPLUS_LPD_SEL_SBU2_400K,
	OPLUS_LPD_SEL_CC1,
	OPLUS_LPD_SEL_CC2,
	OPLUS_LPD_SEL_DP,
	OPLUS_LPD_SEL_DM,
	OPLUS_LPD_SEL_INVALID,
} OPLUS_LPD_SEL_TYPE;

#define OPLUS_LPD_SEL_SBU1_MASK		(1 << OPLUS_LPD_SEL_SBU1)
#define OPLUS_LPD_SEL_SBU2_MASK		(1 << OPLUS_LPD_SEL_SBU2)
#define OPLUS_LPD_SEL_SBU1_PULLUP_MASK	(1 << OPLUS_LPD_SEL_SBU1_400K)
#define OPLUS_LPD_SEL_SBU2_PULLUP_MASK	(1 << OPLUS_LPD_SEL_SBU2_400K)
#define OPLUS_LPD_SEL_CC1_MASK		(1 << OPLUS_LPD_SEL_CC1)
#define OPLUS_LPD_SEL_CC2_MASK		(1 << OPLUS_LPD_SEL_CC2)
#define OPLUS_LPD_SEL_DP_MASK		(1 << OPLUS_LPD_SEL_DP)
#define OPLUS_LPD_SEL_DM_MASK		(1 << OPLUS_LPD_SEL_DM)

#define OPLUS_LPD_NOT_SUPPORT		0
#define OPLUS_LPD_SUPPORT		1
#define OPLUS_LPD_SUPPORT_NOT_SHOW_UI	2

#define OPLUS_LPD_NOT_DETECT		0
#define OPLUS_LPD_DETECT		1
#define OPLUS_LPD_ERROR			2

#define OPLUS_LPD_INFO_LEN		16
#define MAX_LPD_CONFIG_NUM		10
#define MAX_LPD_RANG_NUM		2

#define SMART_CHARGE_USER_USBTEMP	1
#define SMART_CHARGE_USER_OTHER		0

#endif /* __OPLUS_MMS_WIRED_H__ */
